on: [push]
jobs:
    hello_world_job:
      runs-on: ubuntu-latest
      name: A job to say hello
      steps:
        - name: Hellow world action step
          id: hello
          uses: ./dist
          with: 
            who-to-greet: 'Jean Carlo'
        - name: Get the output time
          run: echo "The time was ${{steps.hello.outputs.time}}"